changelog:
  categories:
    - title: "Framework"
      labels:
        - "framework"
    - title: "Compatibility"
      labels:
        - "compat"
        - "transport"
    - title: "Docs"
      labels:
        - "docs"
    - title: "Misc"
      labels:
        - "chore"
        - "refactor"
      exclude:
        labels:
          - "skip-changelog"
