version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
