// Package codegen provides code generation from TL schema.
package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Generator generates Go code from TL schema.
type Generator struct {
	options Options
}

// NewGenerator creates a new generator.
func NewGenerator(options Options) *Generator {
	return &Generator{options: options}
}

// Generate generates Go code from the schema.
func (g *Generator) Generate(schema *Schema) error {
	// Create output directory
	if err := os.MkdirAll(g.options.OutDir, 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	// Generate types file
	if err := g.generateTypes(schema); err != nil {
		return fmt.Errorf("generate types: %w", err)
	}

	// Generate services file
	if err := g.generateServices(schema); err != nil {
		return fmt.Errorf("generate services: %w", err)
	}

	// Generate register file
	if err := g.generateRegister(schema); err != nil {
		return fmt.Errorf("generate register: %w", err)
	}

	return nil
}

func (g *Generator) generateTypes(schema *Schema) error {
	filename := filepath.Join(g.options.OutDir, "types.go")
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintf(file, "// Code generated by tlrpc-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(file, "package %s\n\n", g.options.Package)

	for _, typ := range schema.Types {
		g.generateType(file, typ)
	}

	return nil
}

func (g *Generator) generateServices(schema *Schema) error {
	filename := filepath.Join(g.options.OutDir, "services.go")
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintf(file, "// Code generated by tlrpc-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(file, "package %s\n\n", g.options.Package)

	for _, fn := range schema.Functions {
		g.generateService(file, fn)
	}

	return nil
}

func (g *Generator) generateRegister(schema *Schema) error {
	filename := filepath.Join(g.options.OutDir, "register.go")
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintf(file, "// Code generated by tlrpc-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(file, "package %s\n\n", g.options.Package)

	// TODO: Generate registration functions
	return nil
}

func (g *Generator) generateType(file *os.File, typ *Type) {
	typeName := g.pascalCase(typ.Name)

	fmt.Fprintf(file, "// %s represents %s\n", typeName, typ.Name)
	fmt.Fprintf(file, "type %s struct {\n", typeName)

	for _, param := range typ.Params {
		fieldName := g.pascalCase(param.Name)
		fieldType := g.mapType(param.Type)
		fmt.Fprintf(file, "\t%s %s\n", fieldName, fieldType)
	}

	fmt.Fprintf(file, "}\n\n")
}

func (g *Generator) generateService(file *os.File, fn *Function) {
	serviceName := g.pascalCase(fn.Name)

	fmt.Fprintf(file, "// %sServer represents the %s service\n", serviceName, fn.Name)
	fmt.Fprintf(file, "type %sServer interface {\n", serviceName)

	methodName := g.pascalCase(fn.Name)
	params := g.generateParams(fn.Params)
	resultType := g.mapType(fn.ResultType)

	fmt.Fprintf(file, "\t%s(%s) (%s, error)\n", methodName, params, resultType)
	fmt.Fprintf(file, "}\n\n")
}

func (g *Generator) generateParams(params []*Param) string {
	if len(params) == 0 {
		return ""
	}

	var parts []string
	for _, param := range params {
		paramName := g.pascalCase(param.Name)
		paramType := g.mapType(param.Type)
		parts = append(parts, fmt.Sprintf("%s %s", paramName, paramType))
	}

	return strings.Join(parts, ", ")
}

func (g *Generator) pascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		parts[i] = strings.Title(part)
	}
	return strings.Join(parts, "")
}

func (g *Generator) mapType(tlType string) string {
	// Simple type mapping
	switch tlType {
	case "int":
		return "int32"
	case "long":
		return "int64"
	case "string":
		return "string"
	case "bytes":
		return "[]byte"
	case "Bool":
		return "bool"
	default:
		return g.pascalCase(tlType)
	}
}