// Package codegen provides file writing utilities.
package codegen

import (
	"fmt"
	"os"
	"path/filepath"
)

// Writer handles writing generated files.
type Writer struct {
	outDir string
}

// NewWriter creates a new writer.
func NewWriter(outDir string) *Writer {
	return &Writer{outDir: outDir}
}

// WriteFile writes content to a file.
func (w *Writer) WriteFile(filename, content string) error {
	path := filepath.Join(w.outDir, filename)

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer file.Close()

	if _, err := file.WriteString(content); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	return nil
}

// WriteGeneratedFile writes a generated file with header.
func (w *Writer) WriteGeneratedFile(filename, pkgName, content string) error {
	header := fmt.Sprintf("// Code generated by tlrpc-gen. DO NOT EDIT.\n\npackage %s\n\n", pkgName)
	return w.WriteFile(filename, header+content)
}