package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
)

// FileWriter organizes generated code into files.
type FileWriter struct {
	outDir     string
	pkgName    string
	schemaFile string
	layer      int
	files      map[string]*bytes.Buffer
}

// NewFileWriter creates a new FileWriter.
func NewFileWriter(outDir, pkgName, schemaFile string, layer int) *FileWriter {
	return &FileWriter{
		outDir:     outDir,
		pkgName:    pkgName,
		schemaFile: schemaFile,
		layer:      layer,
		files:      map[string]*bytes.Buffer{},
	}
}

// NewFile returns a writer for a named file.
func (w *FileWriter) NewFile(name string) io.Writer {
	if buf, ok := w.files[name]; ok {
		return buf
	}
	buf := &bytes.Buffer{}
	w.files[name] = buf
	return buf
}

// Files returns the generated file names.
func (w *FileWriter) Files() []string {
	files := make([]string, 0, len(w.files))
	for name := range w.files {
		files = append(files, name)
	}
	return files
}

// WriteAll creates files with headers and content.
func (w *FileWriter) WriteAll() error {
	if err := os.MkdirAll(w.outDir, 0o755); err != nil {
		return err
	}

	for name, buf := range w.files {
		content := w.header(name) + buf.String()
		formatted, err := format.Source([]byte(content))
		if err != nil {
			return fmt.Errorf("format %s: %w", name, err)
		}
		path := filepath.Join(w.outDir, name)
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			return err
		}
	}

	return nil
}

// Format gofmts all generated files on disk.
func (w *FileWriter) Format() error {
	entries, err := os.ReadDir(w.outDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" {
			continue
		}
		path := filepath.Join(w.outDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		formatted, err := format.Source(data)
		if err != nil {
			return fmt.Errorf("format %s: %w", entry.Name(), err)
		}
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func (w *FileWriter) header(filename string) string {
	baseHeader := fmt.Sprintf("// Code generated by tlrpc-gen. DO NOT EDIT.\n// Source: %s\n// Layer: %d\n\npackage %s\n\n", w.schemaFile, w.layer, w.pkgName)

	switch filename {
	case "codec.go":
		return baseHeader + "import (\n\t\"github.com/r6m/tlrpc\"\n\t\"github.com/r6m/tlrpc/types\"\n)\n\n"
	case "services.go", "register.go":
		return baseHeader + "import (\n\t\"context\"\n\t\"errors\"\n\t\"github.com/r6m/tlrpc\"\n)\n\n"
	case "types.go", "interfaces.go":
		return baseHeader + "import (\n\t\"github.com/r6m/tlrpc\"\n\t\"github.com/r6m/tlrpc/types\"\n)\n\n"
	case "requests.go":
		return baseHeader + "import (\n\t\"github.com/r6m/tlrpc\"\n\t\"github.com/r6m/tlrpc/mtproto\"\n\t\"github.com/r6m/tlrpc/types\"\n\t\"io\"\n)\n\n"
	case "constants.go":
		return baseHeader + "// Constructor ID constants\n\n"
	default:
		return baseHeader + "import (\n\t\"context\"\n\t\"errors\"\n\t\"fmt\"\n\t\"io\"\n\t\"github.com/r6m/tlrpc\"\n\t\"github.com/r6m/tlrpc/mtproto\"\n\t\"github.com/r6m/tlrpc/types\"\n)\n\n"
	}
}
