package generator

import (
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFileWriter_WriteAllAndFormat(t *testing.T) {
	dir := t.TempDir()
	digest := fmt.Sprintf("%x", sha256.Sum256([]byte("exact schema input\n")))
	writer := NewFileWriterWithProvenance(dir, "gen", "schema.tl", 222, digest)

	buf := writer.NewFile("types.go")
	if _, err := buf.Write([]byte("type User struct{}\n")); err != nil {
		t.Fatalf("write buffer: %v", err)
	}

	if err := writer.WriteAll(); err != nil {
		t.Fatalf("write all: %v", err)
	}

	path := filepath.Join(dir, "types.go")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read file: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "Code generated by tlrpc-gen") {
		t.Fatalf("expected header in output")
	}
	if !strings.Contains(content, "// Schema SHA-256: "+digest) {
		t.Fatalf("expected schema digest in output")
	}
	if !strings.Contains(content, "// Layer: 222") {
		t.Fatalf("expected exact layer in output")
	}
	if !strings.Contains(content, "package gen") {
		t.Fatalf("expected package in output")
	}

	if err := writer.Format(); err != nil {
		t.Fatalf("format: %v", err)
	}
}

func TestFileWriter_ProvenanceIsDeterministicAcrossFilesAndRuns(t *testing.T) {
	const (
		digest = "00c7e570c184732d1eacb5d6de9155b058bed0e9ea9ad963ea8f5c3c15f44c74"
		layer  = 228
	)
	fileContents := map[string]string{
		"constants.go": "const ConstructorID uint32 = 1\n",
		"types.go":     "type User struct{}\n",
	}

	generate := func(dir string) map[string][]byte {
		t.Helper()
		writer := NewFileWriterWithProvenance(dir, "telegram", "telegram_api.tl", layer, digest)
		for name, content := range fileContents {
			if _, err := io.WriteString(writer.NewFile(name), content); err != nil {
				t.Fatalf("write %s: %v", name, err)
			}
		}
		if err := writer.WriteAll(); err != nil {
			t.Fatalf("write all: %v", err)
		}

		result := make(map[string][]byte, len(fileContents))
		for name := range fileContents {
			data, err := os.ReadFile(filepath.Join(dir, name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			header := "// Schema SHA-256: " + digest + "\n// Layer: 228\n"
			if !strings.Contains(string(data), header) {
				t.Fatalf("%s does not contain deterministic provenance header", name)
			}
			result[name] = data
		}
		return result
	}

	first := generate(t.TempDir())
	second := generate(t.TempDir())
	for name := range fileContents {
		if string(first[name]) != string(second[name]) {
			t.Fatalf("%s differs across identical generation runs", name)
		}
	}
}

func TestNewFileWriter_RemainsCompatible(t *testing.T) {
	writer := NewFileWriter(t.TempDir(), "gen", "schema.tl", 222)
	if got := writer.header("constants.go"); !strings.Contains(got, "// Schema SHA-256: unavailable\n") {
		t.Fatalf("legacy constructor header missing explicit unavailable provenance: %q", got)
	}
}
