package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"go/scanner"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// FileWriter organizes generated code into files.
type FileWriter struct {
	outDir       string
	pkgName      string
	schemaFile   string
	schemaSHA256 string
	layer        int
	files        map[string]*bytes.Buffer
}

// NewFileWriter creates a new FileWriter.
func NewFileWriter(outDir, pkgName, schemaFile string, layer int) *FileWriter {
	return NewFileWriterWithProvenance(outDir, pkgName, schemaFile, layer, "unavailable")
}

// NewFileWriterWithProvenance creates a FileWriter that records the SHA-256
// digest of the exact schema input in every generated file.
func NewFileWriterWithProvenance(outDir, pkgName, schemaFile string, layer int, schemaSHA256 string) *FileWriter {
	return &FileWriter{
		outDir:       outDir,
		pkgName:      pkgName,
		schemaFile:   schemaFile,
		schemaSHA256: schemaSHA256,
		layer:        layer,
		files:        map[string]*bytes.Buffer{},
	}
}

// NewFile returns a writer for a named file.
func (w *FileWriter) NewFile(name string) io.Writer {
	if buf, ok := w.files[name]; ok {
		return buf
	}
	buf := &bytes.Buffer{}
	w.files[name] = buf
	return buf
}

// Files returns the generated file names.
func (w *FileWriter) Files() []string {
	files := make([]string, 0, len(w.files))
	for name := range w.files {
		files = append(files, name)
	}
	return files
}

// WriteAll creates files with headers and content.
func (w *FileWriter) WriteAll() error {
	if err := os.MkdirAll(w.outDir, 0o755); err != nil {
		return err
	}

	for name, buf := range w.files {
		content := w.header(name) + buf.String()
		formatted, err := format.Source([]byte(content))
		if err != nil {
			return fmt.Errorf("format %s: %w", name, err)
		}
		path := filepath.Join(w.outDir, name)
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			return err
		}
	}

	return nil
}

// Format gofmts all generated files on disk.
func (w *FileWriter) Format() error {
	entries, err := os.ReadDir(w.outDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" {
			continue
		}
		path := filepath.Join(w.outDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		formatted, err := format.Source(data)
		if err != nil {
			return fmt.Errorf("format %s: %w", entry.Name(), err)
		}
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func (w *FileWriter) header(filename string) string {
	baseHeader := fmt.Sprintf("// Code generated by tlrpc-gen. DO NOT EDIT.\n// Source: %s\n// Schema SHA-256: %s\n// Layer: %d\n\npackage %s\n\n", w.schemaFile, w.schemaSHA256, w.layer, w.pkgName)

	if filename == "constants.go" {
		return baseHeader + "// Constructor ID constants\n\n"
	}
	body := ""
	if buffer := w.files[filename]; buffer != nil {
		body = buffer.String()
	}
	var imports []string
	externalGroup := false
	qualifiers := packageQualifiers(body)
	for _, candidate := range []struct{ qualifier, path, alias string }{
		{"bytes.", "bytes", ""}, {"context.", "context", ""}, {"errors.", "errors", ""},
		{"fmt.", "fmt", ""}, {"io.", "io", ""},
		{"tlrpc.", "github.com/r6m/tlrpc", ""},
		{"mtproto.", "github.com/r6m/tlrpc/mtproto", ""},
		{"types.", "github.com/r6m/tlrpc/types", ""},
		{"tltypes.", "github.com/r6m/tlrpc/types", "tltypes "},
	} {
		if qualifiers[strings.TrimSuffix(candidate.qualifier, ".")] {
			if !externalGroup && strings.Contains(candidate.path, ".") {
				if len(imports) > 0 {
					imports = append(imports, "\n")
				}
				externalGroup = true
			}
			imports = append(imports, fmt.Sprintf("\t%s%q\n", candidate.alias, candidate.path))
		}
	}
	if len(imports) == 0 {
		return baseHeader
	}
	return baseHeader + "import (\n" + strings.Join(imports, "") + ")\n\n"
}

// Scan Go tokens so comments, schema names in strings, and qualifier suffixes
// cannot introduce unused imports into otherwise valid generated files.
func packageQualifiers(body string) map[string]bool {
	used := make(map[string]bool)
	var scan scanner.Scanner
	file := token.NewFileSet().AddFile("generated", -1, len(body))
	scan.Init(file, []byte(body), nil, 0)
	previous := ""
	for {
		_, tok, literal := scan.Scan()
		if tok == token.EOF {
			return used
		}
		if tok == token.PERIOD && previous != "" {
			used[previous] = true
		}
		previous = ""
		if tok == token.IDENT {
			previous = literal
		}
	}
}
