package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFileWriter_WriteAllAndFormat(t *testing.T) {
	dir := t.TempDir()
	writer := NewFileWriter(dir, "gen", "schema.tl", 222)

	buf := writer.NewFile("types.go")
	if _, err := buf.Write([]byte("type User struct{}\n")); err != nil {
		t.Fatalf("write buffer: %v", err)
	}

	if err := writer.WriteAll(); err != nil {
		t.Fatalf("write all: %v", err)
	}

	path := filepath.Join(dir, "types.go")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read file: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "Code generated by tlrpc-gen") {
		t.Fatalf("expected header in output")
	}
	if !strings.Contains(content, "package gen") {
		t.Fatalf("expected package in output")
	}

	if err := writer.Format(); err != nil {
		t.Fatalf("format: %v", err)
	}
}
